### PR TITLE
pr-add-RishaubKumar

### PR DESCRIPTION
**Pull request by RishaubKumar**
### Description

This pull request introduces the explore.md file, which provides an overview of open-source projects and encourages contributions from the community. The document includes sections on the definition of open source, the benefits of contributing, and a step-by-step guide on how to get started with open-source projects.

The inclusion of a pull request template is also featured, guiding contributors on how to effectively submit their changes.

These changes are necessary to create a welcoming environment for new contributors, offering clear instructions and resources that facilitate their engagement with open-source projects. By providing this information, we aim to enhance community participation, foster collaboration, and support the growth of the open-source ecosystem.

- **Related Issue**: #(18)

### Checklist

Before submitting your pull request, please ensure you have completed the following tasks:
- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and followed the process outlined there.
- [x] I have added tests that prove my fix or feature works as expected (if applicable).
- [x] I have updated necessary documentation (if applicable).
- [x] My changes are free from any merge conflicts.
- [ ] I have added my name and PR details to the `participants/participants.js` file (if contributing in Tier 1 or 2).

### Additional Information

The explore.md file serves as a guide for contributors to understand the principles of open source, the benefits of contributing, and how to get started. It includes sections on:
Overview of Open Source: Defines what open source is and its significance.
Benefits of Contributing: Outlines personal and community advantages of participating.
Getting Started: Provides steps for finding and contributing to projects.
Contribution Guidelines: Details the process for submitting contributions.
Feedback from maintainers and contributors is welcome to enhance this guide further. Please let me know if there are specific areas that need more detail!

### CODE REVIEW

**Comment by RishaubKumar** [comment]
@iamAyushChamoli now I rectified the existing issue and created new pull request with every neccessary correction

**Comment by iamAyushChamoli** [comment]
@RishaubKumar This is not what we are looking for in this file. Please write about what Open Source is and how it contributes to one's growth as a developer and how newcomers can explore open source with hacktoberfest and specifically this repository. Please refrain from using GenAI tools like ChatGPT to submit a PR.

**Comment by RishaubKumar** [comment]
@iamAyushChamoli  now this file highlights Hacktoberfest GEU as a chance for developers to showcase their skills and earn exclusive GitHub badges in collaboration with Vaunt.dev. It provides a step-by-step guide on contributing to the hacktoberfest-24 repository, encouraging newcomers to participate for personal growth and skill development, while also including helpful resource links to assist in the contribution process.

**Comment by RishaubKumar** [comment]
@iamAyushChamoli  I have done all changes please merge

**Pull request merged**
