### PR TITLE
GitHub git learn more

### PR DESCRIPTION
**Pull request by ManishG04**
### Description

I have created the markdown file which is accessed when the user clicks on the learn more button on the Learn Git and GitHub Card on the website. This helps the user understand what is git and GitHub, what is version control, how Hacktoberfest 2024 will help them learn git and GitHub, what they need to know before contributing.

- **Related Issue**:  #20 

### Checklist

Before submitting your pull request, please ensure you have completed the following tasks:
- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and followed the process outlined there.
- [x] I have added tests that prove my fix or feature works as expected (if applicable).
- [x] I have updated necessary documentation (if applicable).
- [x] My changes are free from any merge conflicts.
- [x] I have added my name and PR details to the `participants/participants.js` file (if contributing in Tier 1 or 2).

### CODE REVIEW

**Comment by iamAyushChamoli** [comment]
@ManishG04 Thanks for the PR! Unfortunately some participants were added during the time you worked on the PR and submitted it. Please resubmit a fresh commit by Syncing the fork so that your PR does not introduce a merge conflict. Read [Syncing a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) for more details. Pardon any inconvenience caused.

**Comment by ManishG04** [comment]
Now I think the PR, should not have any merge conflicts, can you now accept it?

**Comment by iamAyushChamoli** [comment]
@ManishG04 please do not update participants.js file until one of your PRs gets successfully merged. Please submit a fresh commit and remove the edits that you made in participants.js and other related files.

**Comment by ManishG04** [comment]
@iamAyushChamoli Sorry for that, In the checklist you mentioned that we have to first update participants and then do PR, now I have removed the changes in the participants.js and other related files.

**Pull request merged**
