### PR TITLE
pr-add-RishaubKumar-83

### PR DESCRIPTION
**Pull request by RishaubKumar**
### Description

This pull request introduces the explore.md file, which provides an overview of open-source projects and encourages contributions from the community. The document includes sections on the definition of open source, the benefits of contributing, and a step-by-step guide on how to get started with open-source projects.

The inclusion of a pull request template is also featured, guiding contributors on how to effectively submit their changes.

These changes are necessary to create a welcoming environment for new contributors, offering clear instructions and resources that facilitate their engagement with open-source projects. By providing this information, we aim to enhance community participation, foster collaboration, and support the growth of the open-source ecosystem.

- **Related Issue**: #(18)

### Checklist

Before submitting your pull request, please ensure you have completed the following tasks:
- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and followed the process outlined there.
- [x] I have added tests that prove my fix or feature works as expected (if applicable).
- [x] I have updated necessary documentation (if applicable).
- [x] My changes are free from any merge conflicts.
- [x] I have added my name and PR details to the `participants/participants.js` file (if contributing in Tier 1 or 2).

### PR Title Convention

Please ensure the PR title follows the required format:
checked

### Screenshots (if applicable)
ss3
ss2
ss1

### Additional Information
The explore.md file serves as a guide for contributors to understand the principles of open source, the benefits of contributing, and how to get started. It includes sections on:

Overview of Open Source: Defines what open source is and its significance.
Benefits of Contributing: Outlines personal and community advantages of participating.
Getting Started: Provides steps for finding and contributing to projects.
Contribution Guidelines: Details the process for submitting contributions.
Feedback from maintainers and contributors is welcome to enhance this guide further. Please let me know if there are specific areas that need more detail!

### CODE REVIEW

**Comment by iamAyushChamoli** [comment]
@RishaubKumar please update the participants.js file only AFTER one of your PR get's merged. For now, please remove the edits that you've made to the participants.js and related files and submit a fresh commit.

**Comment by iamAyushChamoli** [comment]
@RishaubKumar also please reference the related issue properly

**Comment by RishaubKumar** [comment]
Hi @iamAyushChamoli 

I have made the requested changes to my pull request for Issue #18. Could you please review the updates and consider merging it if everything looks good?
If there are any additional modifications or improvements needed, please feel free to let me know, and I will make the necessary changes.

Thank you for your time and guidance!

**Comment by RishaubKumar** [comment]
also please assign this issue to me under hacktoberfest label

**Review by iamAyushChamoli — CHANGES_REQUESTED** [review]
I can still see that you have not completely reversed the changes that you made to the participants.js file and the image that you added. Please recheck it and remove all the changes that you made to the participants.js file and related files.

`import { vineet,hayagreevanv,uday,umesh, mohit ,divyanshu, Rishaub} from "./avatars/index";`

**Comment by RishaubKumar** [comment]
Remove all the changes that I made to the participants.js file and related files

**Comment by iamAyushChamoli** [comment]
@RishaubKumar Please check all the changes well. Alternatively, you can refresh the branch by Syncing the Fork and then making the changes again to remove any changes that might be leading to breaking of the prod.
image

**Pull request closed without merging**
