### PR TITLE
pr-add-RishaubKumar

### PR DESCRIPTION
**Pull request by RishaubKumar**
### Description

This PR refactors the participant system to prevent frequent merge conflicts in the participants.js file. Key changes include:
Separate Participant Files: Each contributor now adds their details in a unique file within the participants/ folder (e.g., participants/vineet.js), avoiding the need for everyone to modify a single file.

- **Related Issue**: #86 

### Checklist

Before submitting your pull request, please ensure you have completed the following tasks:
- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and followed the process outlined there.
- [x] I have added tests that prove my fix or feature works as expected (if applicable).
- [x] I have updated necessary documentation (if applicable).
- [x] My changes are free from any merge conflicts.
- [ ] I have added my name and PR details to the `participants/participants.js` file (if contributing in Tier 1 or 2).

### Screenshots (if applicable)
Screenshot (27)
### Additional Information
New index.js in participants/:
A new index.js file has been created within the participants/ directory. Here individual need to import manually because our app is based on react platform which do not import dynamically for that we need to use api or change entire code.

Removed Old index.js from avatars/:
The previous index.js file located in the avatars/ directory has been deleted to streamline the structure and eliminate redundancy. This change allows for a cleaner and more organized file system, where participant-related data is now solely managed within the participants/ directory.

File Structure Update:
Each contributor now has their own file (e.g., participants/johndoe.js), making it easier to manage individual contributions and minimizing the risk of merge conflicts. This organization allows contributors to work on their files independently, reducing the likelihood of conflicts arising from multiple updates to a single participants.js file.

### CODE REVIEW

**Comment by iamAyushChamoli** [comment]
@RishaubKumar this PR is introducing some merge conflicts that need to be resolved before we can merge it

**Comment by RishaubKumar** [comment]
@iamAyushChamoli I have resolved the merge conflict issue successfully now you can merge it

**Comment by iamAyushChamoli** [comment]
@RishaubKumar thanks, can you also create an updated CONTRIBUTING.md file that explains in depth how participants can add their name in this new system and participate in the leaderboard?

**Comment by RishaubKumar** [comment]
@iamAyushChamoli As per  your instruction I have updated contributing.md By creating a new issue please accept that pull request

**Pull request merged**
